version: "4.25.2"
services:
  app_service:
    container_name: app_gestpacientes_cont
    image: gestpacientes_img:1.0.0
    build:
      context: .
    ports:
      - '8081:8080'
    environment:
      - BD_MySQL=jdbc:mysql://conexionMySQL_service/pacientesdb
      - USUARIO_MySQL=root
      - PASSWORD_MySQL=secreta
    depends_on:
      - conexionMySQL_service
  conexionMySQL_service:
    image: mysql
    container_name: mysql_cont
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=secreta
      - MYSQL_DATABASE=localhost/pacientesdb:3307
    volumes:
      - ../../Recursos/Volumenes/Vol_MySQL:/var/lib/mysql