version: "4.25.2"
services:
  app_service:
    container_name: app_gestinterna_cont
    image: gestinterna_img:1.0.0
    build:
      context: .
    ports:
      - '8083:8080'
    networks:
      TFG_network:
        ipv4_address: 192.168.0.6
networks:
  TFG_network:
    name: TFG_net
    driver: bridge
    external: true
    ipam:
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1